services:
  tests:
    build:
      context: ./frontend
      dockerfile: ./tests/Dockerfile
    depends_on:
      - backend
      - frontend
    networks:
      - aitm-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "38527:38527"
    volumes:
      - ./backend:/app
      - backend-data:/app/data
      # Mount .env file
      - ./.env:/app/.env:ro
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    networks:
      - aitm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:38527/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "59000:59000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://backend:38527/api/v1
    networks:
      - aitm-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:59000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  backend-data:
    driver: local

networks:
  aitm-network:
    driver: bridge
